// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc100.ARobot.subsystems;
import org.usfirst.frc100.ARobot.RobotMap;
import org.usfirst.frc100.ARobot.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Scheduler;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import org.usfirst.frc100.ARobot.Robot;

/**
 *
 */
public class DriveTrain extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
   public SpeedController leftFrontMotor = RobotMap.driveTrainLeftFrontMotor;
    public SpeedController rightFrontMotor = RobotMap.driveTrainRightFrontMotor;
   public  SpeedController leftBackMotor = RobotMap.driveTrainLeftBackMotor;
   public SpeedController rightBackMotor = RobotMap.driveTrainRightBackMotor;
    RobotDrive robotDrive41 = RobotMap.driveTrainRobotDrive41;
   public Encoder leftencoder = RobotMap.driveTrainLeftEncoder;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public Encoder rightencoder = RobotMap.driveTrainRightEncoder;
    double currentrate = 0;
    double previousrate = 0;
    double turnrate = 0;
    Timer timer = new Timer();
    double elapsedtime = .0001;
    double leftstickymax = 1;
    double leftstickymin = -1;
    double leftstickxmax = 1;
    double leftstickxmin = -1;
    double lowerlimit = -100; // prevoius -1250
     double upperlimit = 100; // previous 216

 
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // Set the default command for a subsystem here.
        setDefaultCommand(new Drive());
    }
    
    public void betterArcadeDrive(double x, double y){
        
        SmartDashboard.putNumber("upperlimit", upperlimit);
        SmartDashboard.putNumber("lowerlimit", lowerlimit);
        timer.stop();
    	elapsedtime = timer.get() ;
        currentrate = Robot.driveTrain.leftencoder.getRate();
        if((currentrate - previousrate)/elapsedtime > upperlimit){
        	leftstickymax-=.0005;//check this constant
                leftstickxmax-=.0005;
        	if(leftstickymax < Robot.oi.leftstick.getY()){
        		robotDrive41.arcadeDrive(leftstickymax, y);
                        
        	}
        }else if((currentrate-previousrate)/elapsedtime < lowerlimit){
        	leftstickymin+=.0005;
                leftstickxmin+=.0005;
        	if(leftstickymin < Robot.oi.leftstick.getY()){
        		robotDrive41.arcadeDrive(leftstickymin, y);
        	}
        }else if ((currentrate-previousrate)/elapsedtime < upperlimit && (currentrate-previousrate)/elapsedtime > lowerlimit){
        	leftstickymax = 1;
        	leftstickymin = -1;
                leftstickxmax = 1;
                leftstickxmin = -1;
        }
        
        timer.start();
        SmartDashboard.putNumber("Encoder Pulses",leftencoder.getRaw());
        SmartDashboard.putNumber("Rate", leftencoder.getRate());//same as current rate
        
        SmartDashboard.putNumber("Acceleration", (currentrate-previousrate)/elapsedtime);
        SmartDashboard.putNumber("TrueAcceleration", (leftencoder.getRate() - previousrate)/elapsedtime);
        SmartDashboard.putNumber("Time", elapsedtime);
        SmartDashboard.putNumber("Previous Rate", previousrate);
        SmartDashboard.putNumber("Current Rate", currentrate);
        SmartDashboard.putBoolean("LimitExceeded", (currentrate-previousrate)/elapsedtime > upperlimit );
        SmartDashboard.putNumber("Encoder Value Diff When Turning Right", leftencoder.getRate() - rightencoder.getRate());
        SmartDashboard.putNumber("Encoder Value Diff When Turning Left", rightencoder.getRate() - leftencoder.getRate());
        previousrate = currentrate;
        if(Robot.oi.leftstick.getRawButton(1)) {
            leftencoder.reset();
            rightencoder.reset();
        }
        upperlimit = SmartDashboard.getNumber("upperlimit");
        lowerlimit = SmartDashboard.getNumber("lowerlimit");
        System.out.println(upperlimit);
        robotDrive41.arcadeDrive(x,y);
}
}
