package org.usfirst.frc100.Robot2015.subsystems;

import org.usfirst.frc100.Robot2015.Robot;
import org.usfirst.frc100.Robot2015.RobotMap;
import org.usfirst.frc100.Robot2015.commands.*;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;

/**
 * The claw attached to the elevator used to pick up totes and recycling containers.
 */
public class Claw extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    DoubleSolenoid piston = RobotMap.clawPiston;
    
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    // returns the double Solenoid variable for the open and close claw method
    public boolean isClosed(){
    	return piston.get() == DoubleSolenoid.Value.kForward;
    }
    // The method here opens and closes the claw depending on whether or not it is already closed.
    public void setPiston(boolean closed){
    	if(closed == false){
    		piston.set(DoubleSolenoid.Value.kReverse);
    	}else{
    		piston.set(DoubleSolenoid.Value.kForward);
    	}
    }
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}