// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc100.ARobot;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.PIDSource.PIDSourceParameter;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainLeftFrontMotor;
    public static SpeedController driveTrainRightFrontMotor;
    public static SpeedController driveTrainLeftBackMotor;
    public static SpeedController driveTrainRightBackMotor;
    public static RobotDrive driveTrainRobotDrive41;
    public static Encoder driveTrainLeftEncoder;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
     public static Encoder driveTrainRightEncoder;
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainLeftFrontMotor = new Jaguar(1, 6);
	LiveWindow.addActuator("DriveTrain", "Left Front Motor", (Jaguar) driveTrainLeftFrontMotor);
        
        driveTrainRightFrontMotor = new Jaguar(1, 8);
	LiveWindow.addActuator("DriveTrain", "Right Front Motor", (Jaguar) driveTrainRightFrontMotor);
        
        driveTrainLeftBackMotor = new Jaguar(1, 7);
	LiveWindow.addActuator("DriveTrain", "Left Back Motor", (Jaguar) driveTrainLeftBackMotor);
        
        driveTrainRightBackMotor = new Jaguar(1, 9);
	LiveWindow.addActuator("DriveTrain", "Right Back Motor", (Jaguar) driveTrainRightBackMotor);
        
        driveTrainRobotDrive41 = new RobotDrive(driveTrainLeftFrontMotor, driveTrainLeftBackMotor,
              driveTrainRightFrontMotor, driveTrainRightBackMotor);
	
        driveTrainRobotDrive41.setSafetyEnabled(true);
        driveTrainRobotDrive41.setExpiration(0.1);
        driveTrainRobotDrive41.setSensitivity(0.5);
        driveTrainRobotDrive41.setMaxOutput(1.0);
        driveTrainRobotDrive41.setInvertedMotor(RobotDrive.MotorType.kFrontLeft, true);
        driveTrainRobotDrive41.setInvertedMotor(RobotDrive.MotorType.kRearLeft, true);
        driveTrainRobotDrive41.setInvertedMotor(RobotDrive.MotorType.kFrontRight, true);
        driveTrainRobotDrive41.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);
        driveTrainLeftEncoder = new Encoder(1, 3, 1, 4, false, EncodingType.k4X);
        driveTrainLeftEncoder.setReverseDirection(true);
	LiveWindow.addSensor("DriveTrain", "Left Encoder", driveTrainLeftEncoder);
        driveTrainLeftEncoder.setDistancePerPulse(.0186252);
        driveTrainLeftEncoder.setPIDSourceParameter(PIDSourceParameter.kRate);
        driveTrainLeftEncoder.start();
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainRightEncoder = new Encoder(1, 1, 1, 2, false, EncodingType.k4X);
	LiveWindow.addSensor("DriveTrain", "Right Encoder", driveTrainRightEncoder);
        driveTrainRightEncoder.setReverseDirection(true);
        driveTrainRightEncoder.setDistancePerPulse(.0186252);//find the actual value
        driveTrainRightEncoder.setPIDSourceParameter(PIDSourceParameter.kRate);
        driveTrainRightEncoder.start();
    }
}
