package org.usfirst.frc100.Robot2015.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc100.Robot2015.Robot;

/**
 * Switches to slide or tank drive, depending on the boolean value specified in
 * the constructor ,or toggles if no argument is provided.
 */
public class DeployButterfly extends Command {
	
	boolean toggle = true;
	boolean slide = true;

	// Toggles butterfly pistons, no required subsystems
	public DeployButterfly() {
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	}

	// Sets butterfly pistons to a specific position, no required subsystems
	public DeployButterfly(boolean slideMode) {
		toggle = false;
		slide = slideMode;
	}

	// Called just before this Command runs the first time
	protected void initialize() {
		if (toggle) {
			if (Robot.drivetrain.isSlide()) {
				Robot.drivetrain.switchDrive(false);
			} else {
				Robot.drivetrain.switchDrive(true);
			}
		} else {
			Robot.drivetrain.switchDrive(slide);

		}
	}

	// Called repeatedly when this Command is scheduled to run
	protected void execute() {
	}

	// Make this return true when this Command no longer needs to run execute()
	protected boolean isFinished() {
		return true;
	}

	// Called once after isFinished returns true
	protected void end() {
	}

	// Called when another command which requires one or more of the same
	// subsystems is scheduled to run
	protected void interrupted() {
	}
}
