package org.usfirst.frc100.Robot2015.subsystems;

import org.usfirst.frc100.Robot2015.RobotMap;
import org.usfirst.frc100.Robot2015.commands.*;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

/**
 * The claw attached to the elevator used to pick up totes and recycling containers.
 */
public class Claw extends Subsystem {
	
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    DoubleSolenoid piston = RobotMap.clawPiston;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    }
    
    // Returns whether the claw is closed
    public boolean isClosed(){
    	return piston.get() == DoubleSolenoid.Value.kForward;
    }
    
    // Sets the claw to be open or closed
    public void setPiston(boolean closed){
    	if(!closed){
    		piston.set(DoubleSolenoid.Value.kReverse);
    	} else{
    		piston.set(DoubleSolenoid.Value.kForward);
    	}
    }
    
    // Updates the SmartDashboard
    public void updateDashboard() {
    	SmartDashboard.putBoolean("Claw Closed", isClosed());
    }
}
