////////////////////////////////////////////////////////////////
//                     TEST ON MAIN ROBOT                     //
////////////////////////////////////////////////////////////////

package org.usfirst.frc100.Robot2015.commands;

import org.usfirst.frc100.Robot2015.Preferences;
import org.usfirst.frc100.Robot2015.SlideWinder;
import edu.wpi.first.wpilibj.command.Command;

/**
 * Uses line readers to follow the line autonomously.
 */
public class AutoFollowLine extends Command {
	
	private final double distance;
	
	/**
	 * @param distance - The distance to travel in inches
	 */
    public AutoFollowLine(double distance) {
    	this.distance = distance;
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(SlideWinder.drivetrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	SlideWinder.drivetrain.setLineTrackLimits();
    	SlideWinder.drivetrain.setDistanceTarget(distance);
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	SlideWinder.drivetrain.drive(-SlideWinder.drivetrain.updateDistance(), 0, SlideWinder.drivetrain.followLine());
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return SlideWinder.drivetrain.reachedDistance();
    }

    // Called once after isFinished returns true
    protected void end() {
    	SlideWinder.drivetrain.drive(0, 0, 0);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	end();
    }
}
