package org.usfirst.frc100.Robot2015.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc100.Robot2015.Robot;

/**
 * Manually controls the elevator and arm using the manipulator joystick.
 */
public class ManipulatorManualControl extends Command {

    public ManipulatorManualControl() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.elevator);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.arm);
        setInterruptible(false);
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	Robot.elevator.manualControl(Robot.oi.getManipulatorJoystick().getY());
		Robot.arm.manualControl(Robot.oi.getManipulatorJoystick().getThrottle());
		Robot.arm.setStab(Robot.oi.liftToteButton1.get());
		Robot.arm.setDeploy(Robot.oi.liftToteButton2.get());
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.elevator.activateBrake();
    	Robot.arm.manualControl(0);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	end();
    }
}
