package org.usfirst.frc100.Robot2015.commands;

import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc100.Robot2015.Robot;
import org.usfirst.frc100.Robot2015.subsystems.Arm;

/**
 * Manually controls the elevator using the left manipulator joystick Y-value.
 */
public class  ManualControl extends Command {

	// Requires the Elevator subsystem
    public ManualControl() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.elevator);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.arm);
        setInterruptible(false);
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	Robot.elevator.manualControl(Robot.oi.getManipulatorJoystick().getY());
    	if (Robot.oi.getManipulatorJoystick().getTwist() > 0.5) {
    		Robot.arm.manualControl(Robot.oi.getManipulatorJoystick().getThrottle(), true);
    	} else if (Robot.oi.getManipulatorJoystick().getTwist() < -0.5) {
    		Robot.arm.manualControl(Robot.oi.getManipulatorJoystick().getThrottle(), false);
    	} else {
    		Robot.arm.setArmHeight(Robot.oi.getManipulatorJoystick().getThrottle());
    	}
		Robot.arm.setStab(Robot.oi.calibrateElevatorButton.get());
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.elevator.activateBrake();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
