package org.usfirst.frc100.Robot2015.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc100.Robot2015.Robot;

/**
 * Moves the elevator to an integer height specified in the constructor. 1 is
 * the lowest tote, 2 is the second tote on the stack, 3 is the 3rd tote on the
 * stack, etc. Uses PID.
 */
public class SetElevatorPosition extends Command {
	
	private int position;
	
	/**
	 * @param position - 1 is the lowest tote, 2 is the second tote on the stack,
	 * 3 is the 3rd tote on the stack, etc.
	 */
    public SetElevatorPosition(int position) {
    	this.position = position;
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.elevator);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	Robot.elevator.releaseBrake();
    	Robot.elevator.setPosition(position);
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	Robot.elevator.updatePID();
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return Robot.elevator.isInPosition();
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.elevator.activateBrake();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
