package org.usfirst.frc100.Robot2015.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc100.Robot2015.Robot;

/**
 * Opens the grabbing mechanism on the autonomous arm and terminates
 * immediately. Does not require the subsystem.
 */
public class StabRecycling extends Command {

	private final boolean stab;
	// No required subsystems
	/**
	 * 
	 * @param stab wheather to stab or retract the fingers
	 */
    public StabRecycling(boolean stab) {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    	this.stab = stab;
    }

	// Called just before this Command runs the first time
    protected void initialize() {
    	Robot.arm.setStab(stab);
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return true;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
