package org.usfirst.frc100.Robot2015.commands;

import edu.wpi.first.wpilibj.PowerDistributionPanel;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc100.Robot2015.Robot;

/**
 * Updates the SmartDashboard for all of the subsystems.
 */
public class UpdateDashboard extends Command {
	
	PowerDistributionPanel pdp = new PowerDistributionPanel();

    public UpdateDashboard() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	Robot.arm.updateDashboard();
    	Robot.claw.updateDashboard();
    	Robot.drivetrain.updateDashboard();
    	Robot.elevator.updateDashboard();
    	
    	SmartDashboard.putNumber("PDP Voltage", pdp.getVoltage());
    	for(int i = 0; i < 16; i++){
    		SmartDashboard.putNumber("PDP Port" + i, pdp.getCurrent(i));
    	}
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
