package org.usfirst.frc100.SlideWinder.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc100.SlideWinder.SlideWinder;

/**
 * Autonomously follow the line using vision.
 */
public class  AutoVisionFollowLine extends Command {
	
	private final double distance;

    public AutoVisionFollowLine(double distance) {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(SlideWinder.drivetrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(SlideWinder.cameraVision);
        this.distance = distance;
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	SlideWinder.cameraVision.initCamera();
        SlideWinder.drivetrain.setDistanceTarget(distance);
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	SlideWinder.cameraVision.updateCamera();
    	SlideWinder.drivetrain.visionFollowLine(SlideWinder.cameraVision.getLineOffset());
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return SlideWinder.drivetrain.reachedDistance();
    }

    // Called once after isFinished returns true
    protected void end() {
    	SlideWinder.drivetrain.drive(0, 0, 0);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	end();
    }
}
