package org.usfirst.frc100.SlideWinder.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc100.SlideWinder.Robot;

/**
 * Autonomously follow the line using vision.
 */
public class  AutoVisionFollowLine extends Command {
	
	private final double distance;
	private double lineError = 0;

    public AutoVisionFollowLine(double distance) {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.drivetrain);
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        this.distance = distance;
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	
    	
    	// INITIALIZE CAMERA HERE
    	
    	
    	Robot.drivetrain.setDistanceTarget(distance);
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	
    	
    	// CALCULATE LINE ERROR HERE
    	
    	
    	Robot.drivetrain.visionFollowLine(lineError);
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return Robot.drivetrain.reachedDistance();
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.drivetrain.drive(0, 0, 0);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	end();
    }
}
